# FeedForward Aisles

In [22]:
import pandas as pd
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

In [2]:
train_df = pd.read_csv("data/target-aisles.csv")
target_df = pd.read_csv("data/train-aisles.csv")

In [3]:
train_df.head()

user_id  order_number  size  aisle_air fresheners candles  \
0        1            10     1                             0   
1        2            14     4                             0   
2        3            12     1                             0   
3        4             1     1                             0   
4        5             4     1                             0   

   aisle_asian foods  aisle_baby accessories  aisle_baby bath body care  \
0                  0                       0                          0   
1                  0                       0                          0   
2                  0                       0                          0   
3                  0                       0                          0   
4                  0                       0                          0   

   aisle_baby food formula  aisle_bakery desserts  aisle_baking ingredients  \
0                        0                      0                         0   
1                        0                      0                         0   
2                        0                      0                         0   
3                        0                      0                         0   
4                        0                      0                         0   

       ...       aisle_spreads  aisle_tea  aisle_tofu meat alternatives  \
0      ...                   0          0                             0   
1      ...                   0          0                             0   
2      ...                   0          0                             0   
3      ...                   0          0                             0   
4      ...                   0          0                             0   

   aisle_tortillas flat bread  aisle_trail mix snack mix  \
0                           0                          0   
1                           0                          0   
2                           0                          0   
3                           0                          0   
4                           0                          0   

   aisle_trash bags liners  aisle_vitamins supplements  \
0                        0                           0   
1                        0                           0   
2                        0                           0   
3                        0                           0   
4                        0                           0   

   aisle_water seltzer sparkling water  aisle_white wines  aisle_yogurt  
0                                    0                  0             1  
1                                    0                  0             1  
2                                    1                  0             0  
3                                    1                  0             0  
4                                    0                  0             1  

[5 rows x 137 columns]

In [5]:
X = train_df[train_df.columns[3:]].values

In [7]:
Y = target_df[target_df.columns[3:]].values

In [8]:
X.shape

(206209, 134)

In [9]:
Y.shape

(206209, 134)

# Feed Forward Network

In [18]:
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X.shape[1]))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dense(Y.shape[1], activation='softmax'))


In [19]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy', 'mean_squared_error'])

In [20]:
model.fit(X, Y,
          epochs=10,
          batch_size=128)

Epoch 1/10
206209/206209 [==============================] - 6s 30us/step - loss: 440.3588 - acc: 0.2730 - mean_squared_error: 10.3013
Epoch 2/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.8533 - acc: 0.2766 - mean_squared_error: 10.3006
Epoch 3/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.7068 - acc: 0.2768 - mean_squared_error: 10.3005
Epoch 4/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.6486 - acc: 0.2771 - mean_squared_error: 10.3005
Epoch 5/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.6085 - acc: 0.2771 - mean_squared_error: 10.3005
Epoch 6/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.5846 - acc: 0.2772 - mean_squared_error: 10.3005
Epoch 7/10
206209/206209 [==============================] - 6s 29us/step - loss: 438.5555 - acc: 0.2772 - mean_squared_error: 10.3004
Epoch 8/10
206209/206209 [==============================] - 6s

# Sample Predictions

In [23]:
model.predict(np.array([X[3]]))

array([[1.4124941e-03, 6.1773248e-03, 3.6742401e-04, 3.6092184e-04,
        2.6737854e-03, 2.1286509e-03, 1.0866909e-02, 1.3299078e-03,
        5.0027861e-04, 1.9633227e-03, 2.7230445e-03, 1.7530741e-02,
        8.1482390e-03, 3.4199690e-03, 1.0663036e-03, 5.2624539e-04,
        4.9022702e-03, 9.4953543e-03, 1.3282688e-02, 2.3857800e-03,
        9.2604868e-03, 8.3648451e-03, 3.2970419e-03, 2.5852052e-03,
        1.2009726e-02, 2.5651213e-02, 6.3566263e-03, 1.1936706e-03,
        9.5970118e-03, 1.5730468e-03, 9.1886194e-03, 1.0735969e-02,
        1.5699023e-02, 1.4516755e-02, 1.0222374e-03, 1.0353072e-03,
        1.6393696e-03, 4.4567492e-03, 1.7007987e-03, 3.6720280e-03,
        7.7072289e-03, 1.5587050e-02, 1.3208765e-02, 5.8119185e-03,
        8.3890907e-04, 1.0780361e-03, 1.2792842e-03, 9.3195593e-04,
        3.7222637e-03, 1.3240706e-02, 7.1711168e-02, 1.0852335e-02,
        1.3036231e-03, 5.1485740e-02, 6.4508794e-03, 1.7785316e-03,
        6.3563935e-03, 1.0192348e-03, 2.5538611e

In [24]:
model.predict(np.array([X[10]]))

array([[0.00065177, 0.00598709, 0.00042866, 0.00042415, 0.00771703,
        0.00147057, 0.01057448, 0.00088547, 0.00027644, 0.0010534 ,
        0.00139324, 0.02320337, 0.010251  , 0.00253953, 0.00080329,
        0.00081972, 0.00457016, 0.01046493, 0.00937572, 0.0037687 ,
        0.01024617, 0.00962687, 0.00249777, 0.00147937, 0.01273794,
        0.02190994, 0.00346805, 0.00075398, 0.00775127, 0.00083988,
        0.0079283 , 0.00793366, 0.01588497, 0.0128982 , 0.00056831,
        0.0009881 , 0.00120556, 0.00381475, 0.00122202, 0.00417687,
        0.01009356, 0.01859204, 0.01269703, 0.0032573 , 0.00032607,
        0.00043818, 0.00073664, 0.00038435, 0.00232016, 0.01355812,
        0.07558309, 0.01283471, 0.00162838, 0.05820703, 0.00745167,
        0.00181928, 0.00941716, 0.00082887, 0.00018942, 0.01010997,
        0.0029644 , 0.0060636 , 0.01688997, 0.00324626, 0.00652372,
        0.00574727, 0.00445464, 0.00102383, 0.00284633, 0.00668368,
        0.01156481, 0.01504933, 0.00044896, 0.00

In [25]:
model.predict(np.array([X[11]]))

array([[1.4124941e-03, 6.1773248e-03, 3.6742401e-04, 3.6092184e-04,
        2.6737854e-03, 2.1286509e-03, 1.0866909e-02, 1.3299078e-03,
        5.0027861e-04, 1.9633227e-03, 2.7230445e-03, 1.7530741e-02,
        8.1482390e-03, 3.4199690e-03, 1.0663036e-03, 5.2624539e-04,
        4.9022702e-03, 9.4953543e-03, 1.3282688e-02, 2.3857800e-03,
        9.2604868e-03, 8.3648451e-03, 3.2970419e-03, 2.5852052e-03,
        1.2009726e-02, 2.5651213e-02, 6.3566263e-03, 1.1936706e-03,
        9.5970118e-03, 1.5730468e-03, 9.1886194e-03, 1.0735969e-02,
        1.5699023e-02, 1.4516755e-02, 1.0222374e-03, 1.0353072e-03,
        1.6393696e-03, 4.4567492e-03, 1.7007987e-03, 3.6720280e-03,
        7.7072289e-03, 1.5587050e-02, 1.3208765e-02, 5.8119185e-03,
        8.3890907e-04, 1.0780361e-03, 1.2792842e-03, 9.3195593e-04,
        3.7222637e-03, 1.3240706e-02, 7.1711168e-02, 1.0852335e-02,
        1.3036231e-03, 5.1485740e-02, 6.4508794e-03, 1.7785316e-03,
        6.3563935e-03, 1.0192348e-03, 2.5538611e

In [26]:
model.predict(np.array([X[100]]))

array([[0.00065177, 0.00598709, 0.00042866, 0.00042415, 0.00771703,
        0.00147057, 0.01057448, 0.00088547, 0.00027644, 0.0010534 ,
        0.00139324, 0.02320337, 0.010251  , 0.00253953, 0.00080329,
        0.00081972, 0.00457016, 0.01046493, 0.00937572, 0.0037687 ,
        0.01024617, 0.00962687, 0.00249777, 0.00147937, 0.01273794,
        0.02190994, 0.00346805, 0.00075398, 0.00775127, 0.00083988,
        0.0079283 , 0.00793366, 0.01588497, 0.0128982 , 0.00056831,
        0.0009881 , 0.00120556, 0.00381475, 0.00122202, 0.00417687,
        0.01009356, 0.01859204, 0.01269703, 0.0032573 , 0.00032607,
        0.00043818, 0.00073664, 0.00038435, 0.00232016, 0.01355812,
        0.07558309, 0.01283471, 0.00162838, 0.05820703, 0.00745167,
        0.00181928, 0.00941716, 0.00082887, 0.00018942, 0.01010997,
        0.0029644 , 0.0060636 , 0.01688997, 0.00324626, 0.00652372,
        0.00574727, 0.00445464, 0.00102383, 0.00284633, 0.00668368,
        0.01156481, 0.01504933, 0.00044896, 0.00

In [29]:
model.predict(np.array([X[1050]]))

array([[7.60475057e-04, 3.51610384e-03, 1.20495162e-04, 1.30838162e-04,
        4.54821484e-03, 4.35998011e-03, 8.01759865e-03, 1.18722394e-03,
        1.76808069e-04, 2.32207705e-03, 2.24874122e-03, 2.10841559e-02,
        9.97618306e-03, 3.65841878e-03, 1.04213902e-03, 6.23290107e-05,
        7.96741061e-03, 1.42680332e-02, 1.05501516e-02, 3.08975531e-03,
        7.27555156e-03, 5.69446897e-03, 3.74084734e-03, 2.11285148e-03,
        1.32737234e-02, 3.00609190e-02, 5.65193035e-03, 5.54901781e-04,
        9.90479439e-03, 1.22639979e-03, 7.44518498e-03, 1.33026559e-02,
        1.60095245e-02, 1.21420966e-02, 5.55473089e-04, 1.01247337e-03,
        1.35966716e-03, 2.72808573e-03, 1.50853908e-03, 3.61127197e-03,
        6.33078534e-03, 1.52603630e-02, 8.92022997e-03, 4.15735133e-03,
        1.03454595e-03, 1.18985248e-03, 9.31322691e-04, 8.49934178e-04,
        3.05297086e-03, 1.62023157e-02, 1.09324664e-01, 5.46225253e-03,
        1.73612754e-03, 6.12842217e-02, 9.12975520e-03, 9.537302

# Save Predictions

In [30]:
predictions = model.predict(X)

In [32]:
np.save("data/aisle-predictions", predictions)